mode: "HTTP"
http:
  host: "0.0.0.0"
  port: 9100
  authentication:
    scheme: "NONE"
    username: "username"
    password: "password"
pushGateway:
  job: "unifiedmetrics"
  url: "http://pushgateway:9091"
  authentication:
    scheme: "NONE"
    username: "username"
    password: "password"
  interval: 10